// ===========================
// Constant materials
// ===========================
export const MATERIAL_TYPE = {
  COMMON_CURRENCIES: 'common_currencies',
  CHARACTER_WEAPON_ENHANCEMENT: 'character_weapon_enhancement',
  CHARACTER_TALENT: 'character_talent',
  WEAPON_ENHANCEMENT_MATERIALS: 'weapon_enhancement_materials',
  LOCAL_SPECIALTY: 'local_specialty',
  CHARACTER_EXP: 'character_exp',
  CHARACTER_ASCENTION: 'character_ascention'
};

export const MATERIAL_GROUP = {
  // General Groups
  COMMON_ENEMY_DROPS: 'common_enemy_drops',
  ELITE_ENEMY_DROPS: 'elite_enemy_drops',
  WEAPON_ASCENSION_MATERIALS: 'weapon_ascension_materials',
  TALENT_BOOKS: 'talent_books',
  ASCENSION_GEMS: 'ascension_gems',
  COMMON_ASCENSION_GEMS: 'common_ascension_gems',
  LOCAL_SPECIALTIES: 'local_specialties',
  WEEKLY_BOSS_DROPS: 'weekly_boss_drops',
  NORMAL_BOSS_DROPS: 'normal_boss_drops',
  CROWN_OF_INSIGHT: 'crown_of_insight',

  // Specific ascension gems 
  VAYUDA_TURQUOISE: 'vayuda_turquoise',
  AGNIDUS_AGATE: 'agnidus_agate',
  VARUNADA_LAZURITE: 'varunada_lazurite',
  PRITHIVA_TOPAZ: 'prithiva_topaz',
  VAJRADA_AMETHYST: 'vajrada_amethyst',
  NAGADUS_EMERALD: 'nagadus_emerald',
  SHIVADA_JADE: 'shivada_jade',

  // Specific Enemy Drop Groups
  NOBUSHI_HANDGUARDS: 'nobushi_handguards',
  DAMAGED_MASK: 'damaged_mask',
  HILICHURL_SHOOTER: 'Hilichurl Shooter',
  SAMACHURL: 'samachurl',
  SLIME_MATERIALS: 'slime_materials',
  HUMANOID_RUIN_MACHINE: 'humanoid_ruin_machine',
  TREASURE_HOARDER: 'treasure_hoarder',
  FATUI_SKIRMISHER: 'fatui _skirmisher',
  WHOPPERFLOWER: 'whopperflower',
  SPECTRAL_HUSKS: 'spectral_husks',
  FUNGAL_SPORES: 'fungal_spores',
  INACTIVATED_FUNGAL_NUCLEUS: 'inactivated_fungal_nucleus',
  CONSECRATED_BEAST_PARTS: 'consecrated_beast_parts',
  DESICCATED_SHELLS: 'desiccated_shells',
  CLOCKWORK_GEARS: 'clockwork_gears',
  MEShing_GEAR: 'meshing_gear',
  FATUI_KNIVES: 'fatui_knives',

  // Specific Weapon Ascension Material Groups
  DECARABIAN: 'decarabian',
  BOREAL_WOLF: 'boreal_wolf',
  DANDELION_GLADIATOR: 'dandelion_gladiator',
  GUYUN: 'guyun',
  MIST_VEILED: 'mist_veiled',
  AEROSIDERITE: 'aerosiderite',
  NARUKAMI: 'narukami',
  MASK_OF_THE_WICKED: 'mask_of_the_wicked',
  CORAL_BRANCH: 'coral_branch',
  FOREST_DEW: 'forest_dew',
  OASIS_GARDEN: 'oasis_garden',
  SCORCHING_MIGHT: 'scorching_might',
  ANCIENT_CHORD: 'ancient_chord',
  PURE_SACRED_DEWDROP: 'pure_sacred_dewdrop',
  BROKEN_GOBLET: 'broken_goblet',

  ENHANCEMENT_ORE: 'enhancement_ore',
  FINE_ENHANCEMENT_ORE: 'fine_enhancement_ore',
  MYSTIC_ENHANCEMENT_ORE: 'weapon_enhancement_ore',

  // Weapon Cost Slots (Placeholders for weapon_materials_data)
  WEAPON_ASCENSION_SLOT: 'weapon_ascension_slot',
  COMMON_ENEMY_DROPS_SLOT_1: 'common_enemy_drops_slot_1',
  COMMON_ENEMY_DROPS_SLOT_2: 'common_enemy_drops_slot_2',

  // Local speciality
  WOLFHOOK: 'wolfhook',
  SMALL_LAMP_GRASS: 'small_lamp_grass',
  CECILIA: 'cecilia',
  CALLA_LILY: 'calla_lily',
  VALBERRY: 'valberry',
  PHILANEMO_MUSHROOM: 'philanemo_mushroom',
  WINDWHEEL_ASTER: 'windwheel_aster',
  DANDELION_SEED: 'dandelion_seed',

  JUEYUN_CHILI: 'jueyun_chili',
  NOCTILUCOUS_JADE: 'noctilucous_jade',
  SILK_FLOWER: 'silk_flower',
  GLAZE_LILY: 'glaze_lily',
  COR_LAPIS: 'cor_lapis',

  // Specific talent books group
  BOOKS_FREEDOM: 'books_of_freedom',
  BOOKS_RESISTANCE: 'books_of_resistance',
  BOOKS_BALLAD: 'books_of_ballad',
  BOOKS_PROSPERITY: 'books_of_prosperity',
  BOOKS_DILIGENCE: 'books_of_diligence',
  BOOKS_GOLD: 'books_of_gold',
  BOOKS_TRANSIENCE: 'books_of_transience',
  BOOKS_ELEGANCE: 'books_of_elegance',
  BOOKS_LIGHT: 'books_of_light',
  BOOKS_ADMONITION: 'books_of_admonition',
  BOOKS_INGENUITY: 'books_of_ingenuity',
  BOOKS_PRAXIS: 'books_of_praxis',
  BOOKS_EQUITY: 'books_of_equity',
  BOOKS_JUSTICE: 'books_of_justice',
  BOOKS_ORDER: 'books_of_order',


  // Specific normal boss drops group
  CLEANSING_HEART: 'cleansing_heart',
  EVERFLAME_SEED: 'everflame_seed',
  HOARFROST_CORE: 'hoarfrost_core',
  LIGHTNING_PRISM: 'lightning_prism',

  HURRICANE_SEED: 'hurricane_seed',

  
  DVALIN_MATERIALS:  'dvalin_Materials',

  DVALINS_SIGH: 'dvalins_sigh',
  DVALINS_CLAW: 'dvalins_claw',
  DVALINS_PLUME: 'dvalins_plume',

  SPIRIT_LOCKET_OF_BOREAS: 'spirit_locket_of_boreas',
  RING_OF_BOREAS: 'ring_of_boreas',
  TAIL_OF_BOREAS: 'tail_of_boreas',

  PRISMATIC_SEVERED_TAIL: 'prismatic_severed_tail',
  ASCENDED_SAMPLE_QUEEN: 'ascended_sample_queen'
};


//PRISMATIC_SEVERED_TAIL: 'prismatic_severed_tail',
  //ASCENDED_SAMPLE_QUEEN: 'ascended_sample_queen',
//  TALISMAN_OF_THE_ENIGMATIC_LAND: 'talisman_of_the_enigmatic_land',
  //BERYL_CONCH: 'beryl_conch',
  //SECRET_SOURCE_AIRFLOW_ACCUMULATOR: 'secret_source_airflow_accumulator',
  ///EVERGLOOM_RING: 'evergloom_ring',
  //WORLDSPAN_FERN: 'worldspan_fern',
  //LUMIDOUCE_BELL: 'lumidouce_bell',
  //LIGHTLESS_EYE_OF_THE_MAELSTROM: 'lightless_eye_of_the_maelstrom',
  //QUENEPA_BERRY: 'quenepa_berry',
  //DENIAL_AND_JUDGMENT: 'denial_and_judgment',
  
  //CLEARWATER_JADE: 'clearwater_jade',
  //CLOUDSEAM_SCALE: 'cloudseam_scale',
  //SKYSPLIT_GEMBLOOM: 'skysplit_gembloom',
  //ROMARITIME_FLOWER: 'romaritime_flower',
  //WATER_THAT_FAILED_TO_TRANSCEND: 'water_that_failed_to_transcend',
  //TRISHIRAITE: 'trishiraite',
  //WINTER_ICELEA: 'winter_icelea',
  //LAKELIGHT_LILY: 'lakelight_lily',
  //ARTIFICED_SPARE_CLOCKWORK_COMPONENT_COPPELIUS: 'artificed_spare_clockwork_component_coppelius',
  //LIGHTLESS_MASS: 'lightless_mass',
  //EMPERORS_RESOLUTION: 'emperors_resolution',
  //DRACOLITE: 'dracolite',
  //PINE_AMBER: 'pine_amber',
  //GLOWING_HORNSHROOM: 'glowing_hornshroom',
  //PORTABLE_BEARING: 'portable_bearing',
  //MOURNING_FLOWER: 'mourning_flower',
  //SAURIAN_CLAW_SUCCULENT: 'saurian_claw_succulent',
  //SPRING_OF_THE_FIRST_DEWDROP: 'spring_of_the_first_dewdrop',
  //SPRAYFEATHER_GILL: 'sprayfeather_gill',
  //RAINBOW_ROSE: 'rainbow_rose',
  //ELIXIR_OF_THE_HERETIC: 'elixir_of_the_heretic',
  //CHAOS_AXIS: 'chaos_axis',
  //CHAOS_BOLT: 'chaos_bolt',
  //CHAOS_MODULE: 'chaos_module',
  //CHAOS_OCULUS: 'chaos_oculus',
  //CHAOS_STORAGE: 'chaos_storage',
  //DEAD_LEY_LINE_BRANCH: 'dead_ley_line_branch',
  //DEAD_LEY_LINE_LEAVES: 'dead_ley_line_leaves',
  
  //LEY_LINE_SPROUT: 'ley_line_sprout',
 
  //HUNTERS_SACRIFICIAL_KNIFE: 'hunters_sacrificial_knife',
  //AGENTS_SACRIFICIAL_KNIFE: 'agents_sacrificial_knife',
  //INSPECTORS_SACRIFICIAL_KNIFE: 'inspectors_sacrificial_knife',
  //HEAVY_HORN: 'heavy_horn',
  //BLACK_BRONZE_HORN: 'black_bronze_horn',
  //BLACK_CRYSTAL_HORN: 'black_crystal_horn',
  //CONCEALED_CLAW: 'concealed_claw',
  //CONCEALED_UNGUIS: 'concealed_unguis',
  //CONCEALED_TALON: 'concealed_talon',
  //ARTFUL_DEVICE_FRAGMENT: 'artful_device_fragment',
  //FADED_FLAMING_HILT: 'faded_flaming_hilt',
  //FRACTURED_FLAMING_HILT: 'fractured_flaming_hilt',
  //JEWELED_FLAMING_HILT: 'jeweled_flaming_hilt',
  //GLOOMY_STATUETTE: 'gloomy_statuette',
  //DARK_STATUETTE: 'dark_statuette',
  //DEATHLY_STATUETTE: 'deathly_statuette',
  //NIGHT_WINDS_MYSTIC_CONSIDERATION: 'night_winds_mystic_consideration',
  //AXIS_OF_THE_SECRET_SOURCE: 'axis_of_the_secret_source',
  //SHEATH_OF_THE_SECRET_SOURCE: 'sheath_of_the_secret_source',
  //HEART_OF_THE_SECRET_SOURCE: 'heart_of_the_secret_source',
  //REFRACTIVE_BUD: 'refractive_bud',
  //BEWILDERING_BROADLEAF: 'bewildering_broadleaf',
  //ILLUSORY_LEAFCOIL: 'illusory_leafcoil',
 